"""Bootstrap the whole pipeline to measure how sure each call is.

Brill, Yurko & Wyner (2025) show that many 4th-down "edges" are smaller than
the model's own uncertainty. This script resamples whole games with
replacement, refits every component (WP, conversion, field goal, punt, clock)
on each resample, and writes the replicate models. The app and the coach
grader then report the share of replicates that agree with a call.

Games are resampled whole, because plays in one game share one outcome. Brill
et al. also resample drives within games; this script does not (see the white
paper, section 6).

Run:  py engine/bootstrap.py      (after engine/fit_models.py; ~1 min per replicate)
Out:  app/bootstrap.js
"""
import json
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import CONFIG                               # noqa: E402
from load_data import ROOT, fill_outdoor_weather, load  # noqa: E402
from fit_models import build, snaps                      # noqa: E402

KEEP = ["wp", "conv", "gain", "play", "fg", "punt", "clock", "kickoff_start", "rules"]


def main():
    shipped = json.load(open(os.path.join(ROOT, "data", "model.json")))
    prior = shipped["fg"]["kicker_prior"]
    era = shipped["fg"]["era"]
    df = load()
    df, _ = fill_outdoor_weather(df)
    s = snaps(df)
    games = df["game_id"].unique()
    dfi, si = df.set_index("game_id"), s.set_index("game_id")
    rng = np.random.default_rng(CONFIG["bootstrap_seed"])
    reps = []
    for b in range(CONFIG["bootstrap_models"]):
        t0 = time.time()
        pick = rng.choice(games, size=len(games), replace=True)
        df_b = dfi.loc[pick].reset_index()
        s_b = si.loc[pick].reset_index()
        m = build(df_b, s_b, kicker_prior=prior, ko_df=df, fg_era=era)
        rep = {k: m[k] for k in KEEP}
        rep["fg"] = {"models": m["fg"]["models"]}     # kicker skill comes from the shipped model
        reps.append(rep)
        print(f"replicate {b + 1}/{CONFIG['bootstrap_models']} in {time.time() - t0:.0f}s", flush=True)
    with open(os.path.join(ROOT, "app", "bootstrap.js"), "w") as fh:
        fh.write("// Generated by engine/bootstrap.py. Do not edit by hand.\n")
        fh.write(f"// {len(reps)} game-resampled replicate models, version {CONFIG['version']}.\n")
        fh.write("const BOOT = " + json.dumps(reps, separators=(",", ":")) + ";\n")
        fh.write("if (typeof module !== 'undefined') module.exports = BOOT;\n")


if __name__ == "__main__":
    main()
